2025-04-29 21:25:46,391 : INFO : Start of Training
2025-04-29 21:25:46,391 : INFO : Run_id:2025-04-29_212546_719795624
2025-04-29 21:25:46,391 : INFO : Start of Data Load, validation and transformation
2025-04-29 21:25:46,391 : INFO : Start of Archiving Old Rejected Files...
2025-04-29 21:25:46,391 : INFO : End of Archiving Old Rejected Files...
2025-04-29 21:25:46,391 : INFO : Start of Archiving Old Validated Files...
2025-04-29 21:25:46,392 : INFO : End of Archiving Old Validated Files...
2025-04-29 21:25:46,392 : INFO : Start of Archiving Old Processed Files...
2025-04-29 21:25:46,392 : INFO : End of Archiving Old Processed Files...
2025-04-29 21:25:46,392 : INFO : Start of Archiving Old Result Files...
2025-04-29 21:25:46,392 : INFO : End of Archiving Old Result Files...
2025-04-29 21:25:46,392 : INFO : Start of Reading values From Schema...
2025-04-29 21:25:46,392 : INFO : End of Reading values From Schema...
2025-04-29 21:25:46,392 : INFO : Start of Validating Column Length...
2025-04-29 21:25:46,392 : INFO : End of Validating Column Length...
2025-04-29 21:25:46,393 : INFO : Start of Validating Missing Values...
2025-04-29 21:25:46,393 : INFO : End of Validating Missing Values...
2025-04-29 21:25:46,393 : INFO : Start of Replacing Missing Values with NULL...
2025-04-29 21:25:46,393 : INFO : End of Replacing Missing Values with NULL...
2025-04-29 21:25:46,393 : INFO : Start of Creating Table...
2025-04-29 21:25:46,395 : INFO : Opened training database successfully
2025-04-29 21:25:46,396 : INFO : Tables created successfully
2025-04-29 21:25:46,396 : INFO : Closed training database successfully
2025-04-29 21:25:46,396 : INFO : End of Creating Table...
2025-04-29 21:25:46,396 : INFO : Opened training database successfully
2025-04-29 21:25:46,396 : INFO : Start of Inserting Data into Table...
2025-04-29 21:25:46,396 : INFO : End of Inserting Data into Table...
2025-04-29 21:25:46,396 : INFO : Start of Exporting Data into CSV...
2025-04-29 21:25:46,396 : INFO : Opened training database successfully
2025-04-29 21:25:46,423 : INFO : End of Exporting Data into CSV...
2025-04-29 21:25:46,424 : INFO : Start of Moving Processed Files...
2025-04-29 21:25:46,424 : INFO : End of Moving Processed Files...
2025-04-29 21:25:46,424 : INFO : End of Data Load, validation and transformation
2025-04-29 21:25:46,424 : INFO : Start of Preprocessing...
2025-04-29 21:25:46,424 : INFO : Start of reading dataset...
2025-04-29 21:25:46,432 : INFO : End of reading dataset...
2025-04-29 21:25:46,432 : INFO : Start of Droping Columns...
2025-04-29 21:25:46,435 : INFO : End of Droping Columns...
2025-04-29 21:25:46,435 : INFO : Start of feature encoding...
2025-04-29 21:25:46,437 : INFO : End of feature encoding...
2025-04-29 21:25:46,437 : INFO : Start of Droping Columns...
2025-04-29 21:25:46,438 : INFO : End of Droping Columns...
2025-04-29 21:25:46,438 : INFO : Start of finding missing values...
2025-04-29 21:25:46,440 : INFO : End of finding missing values...
2025-04-29 21:25:46,440 : INFO : Start of imputing missing values...
2025-04-29 21:25:46,450 : INFO : End of imputing missing values...
2025-04-29 21:25:46,450 : INFO : Start of splitting features and label ...
2025-04-29 21:25:46,450 : INFO : End of splitting features and label ...
2025-04-29 21:25:46,450 : INFO : End of Preprocessing...
2025-04-29 21:25:46,450 : INFO : Start of elbow plotting...
2025-04-29 21:25:47,412 : ERROR : Exception raised while elbow plotting:name 'number_of_clusters' is not defined
Traceback (most recent call last):
  File "/Users/sujairibrahim/ML-Projects/Employee Retention/apps/tuning/cluster.py", line 68, in elbow_plot
    self.logger.info('Successfully created ' + str(number_of_clusters) + ' clusters.')
NameError: name 'number_of_clusters' is not defined
2025-04-29 21:25:47,413 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "/Users/sujairibrahim/ML-Projects/Employee Retention/apps/tuning/cluster.py", line 68, in elbow_plot
    self.logger.info('Successfully created ' + str(number_of_clusters) + ' clusters.')
NameError: name 'number_of_clusters' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sujairibrahim/ML-Projects/Employee Retention/apps/training/train_model.py", line 66, in training_model
    number_of_clusters = self.cluster.elbow_plot(self.X)
  File "/Users/sujairibrahim/ML-Projects/Employee Retention/apps/tuning/cluster.py", line 75, in elbow_plot
    raise Exception()
Exception
